spring.application.name=demo

# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.97.2:5432/demo_db
spring.datasource.username=postgres
spring.datasource.password=123qwe
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
